/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IGU.Logueo;

import IGU.Menu.MenuPrincipal;
import Logica.Controladora;
import Persistencia.Conexion.MongoOAD;
import org.bson.Document;

import java.awt.BorderLayout;

/**
 *
 * @author hp
 */
public class InicioSesion extends javax.swing.JPanel {
    private MongoOAD mongoClient;
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion(MongoOAD mongoClient) {
        initComponents();
        mongoClient = mongoClient;
        control = new Controladora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        correo_electronico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        MensajeError = new javax.swing.JLabel();
        BotonIniciarSesion = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar sesion");

        jLabel2.setText("Correo electronico:");

        correo_electronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo_electronicoActionPerformed(evt);
            }
        });

        jLabel3.setText("Contraseña:");

        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        MensajeError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MensajeError.setForeground(new java.awt.Color(255, 0, 0));
        MensajeError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeError.setText("         ");

        BotonIniciarSesion.setText("Iniciar sesion");
        BotonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(correo_electronico)
                    .addComponent(contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(BotonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(correo_electronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(MensajeError)
                .addGap(30, 30, 30)
                .addComponent(BotonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarSesionActionPerformed
        final Document user = mongoClient.getUserById("665dc3b4f5a86a77968cf4b0");
        this.MensajeError.setText(user.toString());
        //        if (control.getUsuario().getCorreo().equals(correo_electronico.getText()) && control.getUsuario().getContraseña().equals(contraseña.getText())){
//            MenuPrincipal mp = new MenuPrincipal();
//            mp.setSize(800, 500);
//            mp.setLocation(0, 0);
//
//            this.removeAll();
//            this.add(mp,BorderLayout.CENTER);
//            this.revalidate();
//            this.repaint();
    }//GEN-LAST:event_BotonIniciarSesionActionPerformed

    private void correo_electronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo_electronicoActionPerformed
        contraseña.requestFocus();
    }//GEN-LAST:event_correo_electronicoActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        BotonIniciarSesionActionPerformed(evt);
    }//GEN-LAST:event_contraseñaActionPerformed

    private Controladora control;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniciarSesion;
    private javax.swing.JLabel MensajeError;
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField correo_electronico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
