/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IGU.Menu;

import IGU.Producto.PaginaProducto;
import Logica.Controladora;
import Logica.Producto;
import Logica.Usuario;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class PaginaInicio extends javax.swing.JPanel {

    /**
     * Creates new form PaginaInicio
     */
    public PaginaInicio() {
        initComponents();
        
        control = new Controladora();
        this.usuario = control.getUsuario();
        indice = 0;
        InicializarCatalogo(indice);
        this.BotonAnterior.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonSiguiente = new javax.swing.JButton();
        BotonAnterior = new javax.swing.JButton();
        Producto1 = new javax.swing.JPanel();
        Producto2 = new javax.swing.JPanel();
        Producto3 = new javax.swing.JPanel();
        Mensaje = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");

        BotonSiguiente.setText("Siguiente");
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });

        BotonAnterior.setText("Anterior");
        BotonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnteriorActionPerformed(evt);
            }
        });

        Producto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Producto1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Producto1Layout = new javax.swing.GroupLayout(Producto1);
        Producto1.setLayout(Producto1Layout);
        Producto1Layout.setHorizontalGroup(
            Producto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        Producto1Layout.setVerticalGroup(
            Producto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Producto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Producto2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Producto2Layout = new javax.swing.GroupLayout(Producto2);
        Producto2.setLayout(Producto2Layout);
        Producto2Layout.setHorizontalGroup(
            Producto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        Producto2Layout.setVerticalGroup(
            Producto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Producto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Producto3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Producto3Layout = new javax.swing.GroupLayout(Producto3);
        Producto3.setLayout(Producto3Layout);
        Producto3Layout.setHorizontalGroup(
            Producto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        Producto3Layout.setVerticalGroup(
            Producto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        Mensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mensaje.setText("                  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonAnterior)
                .addGap(47, 47, 47)
                .addComponent(Producto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(Producto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Producto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(BotonSiguiente)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(BotonSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(BotonAnterior))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Producto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Producto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Producto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
        if (indice < control.stock.size()){
            InicializarCatalogo(indice);
            this.BotonAnterior.setEnabled(true);
        }
        else{
        }
        
        if (indice >= control.stock.size()){
            this.BotonSiguiente.setEnabled(false);
        }
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    private void BotonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnteriorActionPerformed
        if (indice != 3){
            AtrasCatalogo(indice);
            this.BotonSiguiente.setEnabled(true);
        }
        else{}
        
        if (indice == 3)
            this.BotonAnterior.setEnabled(false);
    }//GEN-LAST:event_BotonAnteriorActionPerformed

    private void Producto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Producto1MouseClicked
        AgregarCarrito((PaginaProducto) this.Producto1);
    }//GEN-LAST:event_Producto1MouseClicked

    private void Producto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Producto2MouseClicked
        if (this.Producto2.getClass() == PaginaProducto.class)
            AgregarCarrito((PaginaProducto) this.Producto2);
    }//GEN-LAST:event_Producto2MouseClicked

    private void Producto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Producto3MouseClicked
        if (this.Producto3.getClass() == PaginaProducto.class)
            AgregarCarrito((PaginaProducto) this.Producto3);
    }//GEN-LAST:event_Producto3MouseClicked

    
    private void InicializarItems(JPanel panel,JPanel p2){
        p2.setSize(150,250);
        p2.setLocation(0,0);
        
        panel.removeAll();
        panel.add(p2,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }

    private void InicializarCatalogo(int i){
        JPanel[] paneles = {this.Producto1, this.Producto2, this.Producto3};
        int var = i;
        Producto produc;
        for (JPanel p:paneles){
            if (control.stock.size() > var){
                produc = control.stock.get(var);
               // PaginaProducto pp = new PaginaProducto(produc.getTitulo(),produc.getDescripcion(),produc.getId_producto());
              //  InicializarItems(p,pp);
            }
            else{
                JPanel jp = new JPanel();
                InicializarItems(p,jp);
            }
            var++;
        }
        this.indice = var;
    }
    
    private void AtrasCatalogo(int i){
        JPanel[] paneles = {this.Producto1, this.Producto2, this.Producto3};
        int var = i - 6;
        Producto produc;
        for (JPanel p:paneles){
            produc = control.stock.get(var);
          //  PaginaProducto pp = new PaginaProducto(produc.getTitulo(),produc.getDescripcion(),produc.getId_producto());
          //  InicializarItems(p,pp);
            var++;
        }
        this.indice = var;
    }
    
    private void AgregarCarrito(PaginaProducto pp){
        int producto_id = pp.getId();
        Producto prod = control.stock.get(producto_id);
        if (!usuario.ExisteEnCarrito(prod))
            usuario.AgregarCarrito(prod);
       // Producto f = usuario.BuscarCarrito(producto_id);
      //  f.setCantidad(prod.getCantidad()+1);
    }
    private Controladora control;
    private int indice;
    private Usuario usuario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnterior;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JPanel Producto1;
    private javax.swing.JPanel Producto2;
    private javax.swing.JPanel Producto3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
