/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IGU.Pago;

import javax.swing.JRadioButton;

/**
 *
 * @author hp
 */
public class PaginaPago extends javax.swing.JPanel {

    /**
     * Creates new form PaginaPago
     */
    public PaginaPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumen_compra = new javax.swing.JTextArea();
        total_compra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tarjeta_de_credito = new javax.swing.JRadioButton();
        tarjeta_de_debito = new javax.swing.JRadioButton();
        efectivo = new javax.swing.JRadioButton();
        BotonFinalizar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Finalizar Compra");

        jLabel2.setText("Productos:");

        resumen_compra.setColumns(20);
        resumen_compra.setRows(5);
        jScrollPane1.setViewportView(resumen_compra);

        total_compra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        total_compra.setText("Total:");

        jLabel4.setText("Seleccione su metodo de pago: ");

        tarjeta_de_credito.setText("Tarjeta de credito");
        tarjeta_de_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjeta_de_creditoActionPerformed(evt);
            }
        });

        tarjeta_de_debito.setText("Tarjeta de debito");
        tarjeta_de_debito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjeta_de_debitoActionPerformed(evt);
            }
        });

        efectivo.setText("Efectivo");
        efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectivoActionPerformed(evt);
            }
        });

        BotonFinalizar.setText("Finalizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(total_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(522, 522, 522)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(tarjeta_de_credito)
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tarjeta_de_debito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(149, 149, 149)
                        .addComponent(efectivo)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(total_compra)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarjeta_de_credito)
                    .addComponent(tarjeta_de_debito)
                    .addComponent(efectivo))
                .addGap(18, 18, 18)
                .addComponent(BotonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tarjeta_de_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjeta_de_creditoActionPerformed
        Deseleccionar(tarjeta_de_debito,efectivo);
    }//GEN-LAST:event_tarjeta_de_creditoActionPerformed

    private void tarjeta_de_debitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjeta_de_debitoActionPerformed
        Deseleccionar(tarjeta_de_credito,efectivo);
    }//GEN-LAST:event_tarjeta_de_debitoActionPerformed

    private void efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectivoActionPerformed
        Deseleccionar(tarjeta_de_debito,tarjeta_de_credito);
    }//GEN-LAST:event_efectivoActionPerformed

    private void Deseleccionar(JRadioButton r1, JRadioButton r2){
        r1.setSelected(false);
        r2.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonFinalizar;
    private javax.swing.JRadioButton efectivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resumen_compra;
    private javax.swing.JRadioButton tarjeta_de_credito;
    private javax.swing.JRadioButton tarjeta_de_debito;
    private javax.swing.JLabel total_compra;
    // End of variables declaration//GEN-END:variables
}
